#!/bin/sh
set -e

cmake -DCMAKE_BUILD_TYPE:STRING=Debug -Bbuild

cmake --build build --config Debug --target all

GTEST_COLOR=1 ctest --test-dir build -V

gcovr --filter "(parser/src/.*|parser/include/.*)" --fail-under-line 100
